---
- name: rabbitmq_queues | creating queue(s)
  command: rabbitmqadmin declare queue name={{ item.name }} durable={{ item.durable|lower }}
  run_once: true
  with_items: "{{ rabbitmq_queues }}"
  when: "rabbitmq_queues|length > 0"

- name: rabbitmq_queues | setting up ha on queue(s)
  rabbitmq_policy:
    name: "ha-all"
    pattern: "{{ item.name }}"
    tags: "{{ item.tags }}"
    state: present
  run_once: true
  with_items: "{{ rabbitmq_queues }}"
  when: "rabbitmq_queues|length > 0"

- name: rabbitmq_queues | creating exchange(s)
  command: rabbitmqadmin declare exchange name={{ item.exchange_name }} type={{ item.type }}
  run_once: true
  with_items: "{{ rabbitmq_queues }}"
  when: "rabbitmq_queues|length > 0 and item.exchange_name is defined"

- name: rabbitmq_queues | creating binding(s)
  command: rabbitmqadmin declare binding source={{ item.exchange_name }} destination_type="queue" destination={{ item.name }} routing_key={{ item.routing_key }}
  run_once: true
  with_items: "{{ rabbitmq_queues }}"
  when: "rabbitmq_queues|length > 0 and item.exchange_name is defined"
