---
- name: rabbitmq vhosts | creating vHosts in non-clustered version
  rabbitmq_vhost: name={{ item.name }} state=present
  with_items: "{{ rabbitmq_vhosts }}"
  when: "rabbitmq_vhosts|length > 0 and ((enable_rabbitmq_clustering is defined and not enable_rabbitmq_clustering) or enable_rabbitmq_clustering is not defined)"

- name: rabbitmq vhosts | creating vHosts in clustered version
  rabbitmq_vhost: name={{ item.name }} state=present
  with_items: "{{ rabbitmq_vhosts }}"
  run_once: yes
  when: "rabbitmq_vhosts|length > 0 and (enable_rabbitmq_clustering is defined and enable_rabbitmq_clustering)"

- name: rabbitmq vhosts | setting up ha on vhost(s)
  rabbitmq_policy:
    name: "ha-all"
    pattern: ""
    tags: "{{ item.tags }}"
    vhost: "{{ item.name }}"
    state: present
  run_once: true
  with_items: "{{ rabbitmq_vhosts }}"
  when: "rabbitmq_vhosts|length > 0"
